[phases.setup]
nixPkgs = ['python39', 'nodejs', 'npm']

[phases.install]
cmds = [
    'cd backend && pip install -r requirements.txt',
    'cd frontend && npm install && npm run build'
]

[phases.build]
cmds = ['echo "Build completed"']

[start]
cmd = 'cd backend && python app.py'
