"""se creo modelo baja

Revision ID: 4101e8f1e149
Revises: 6c28ae55402f
Create Date: 2025-08-16 10:34:30.085450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4101e8f1e149'
down_revision = '6c28ae55402f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libros_bajas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('libros_bajas_libro_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'libros', ['libro_id'], ['id'], referent_schema='stock_charles_schema')

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.alter_column('isbn',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('pedidos_isbn_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('pedidos_isbn_key'), ['isbn'])
        batch_op.alter_column('isbn',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)

    with op.batch_alter_table('libros_bajas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('libros_bajas_libro_id_fkey'), 'libros', ['libro_id'], ['id'])

    # ### end Alembic commands ###
