"""se agregó campo editorial a pedido

Revision ID: 41e457b62cbe
Revises: 8cd47d2c2c20
Create Date: 2025-08-19 08:21:41.597928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41e457b62cbe'
down_revision = '8cd47d2c2c20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libros_bajas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('libros_bajas_libro_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'libros', ['libro_id'], ['id'], referent_schema='stock_charles_schema')

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('editorial', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('editorial')

    with op.batch_alter_table('libros_bajas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('libros_bajas_libro_id_fkey'), 'libros', ['libro_id'], ['id'])

    # ### end Alembic commands ###
