"""inicializando migraciones

Revision ID: 6c28ae55402f
Revises: 
Create Date: 2025-08-13 11:14:20.247317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c28ae55402f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('motivo', sa.String(length=250), nullable=True))
        batch_op.alter_column('cantidad',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('isbn',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
        batch_op.create_unique_constraint(None, ['isbn'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('isbn',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
        batch_op.alter_column('cantidad',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('motivo')
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
