"""se agregó campo fecha_vine a pedidos

Revision ID: 8cd47d2c2c20
Revises: 4101e8f1e149
Create Date: 2025-08-18 08:33:37.468787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd47d2c2c20'
down_revision = '4101e8f1e149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libros_bajas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('libros_bajas_libro_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'libros', ['libro_id'], ['id'], referent_schema='stock_charles_schema')

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_viene', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('fecha_viene')

    with op.batch_alter_table('libros_bajas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('libros_bajas_libro_id_fkey'), 'libros', ['libro_id'], ['id'])

    # ### end Alembic commands ###
