"""turno + fecha en CajaTurno

Revision ID: c4d97dbef3fb
Revises: dd8f75594e79
Create Date: 2025-08-20 18:54:51.845936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4d97dbef3fb'
down_revision = 'dd8f75594e79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auditoria_eventos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('auditoria_eventos_usuario_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'], referent_schema='stock_charles_schema')

    with op.batch_alter_table('caja_arqueos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('caja_arqueos_turno_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('caja_arqueos_realizado_por_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['realizado_por_id'], ['id'], referent_schema='stock_charles_schema')
        batch_op.create_foreign_key(None, 'caja_turnos', ['turno_id'], ['id'], referent_schema='stock_charles_schema')

    with op.batch_alter_table('caja_inicio_detalles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('caja_inicio_detalles_turno_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('caja_inicio_detalles_editado_por_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'caja_turnos', ['turno_id'], ['id'], referent_schema='stock_charles_schema')
        batch_op.create_foreign_key(None, 'usuarios', ['editado_por_id'], ['id'], referent_schema='stock_charles_schema')

    with op.batch_alter_table('caja_movimientos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('caja_movimientos_turno_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('caja_movimientos_eliminado_por_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('caja_movimientos_anulado_por_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('caja_movimientos_editado_por_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('caja_movimientos_creado_por_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('caja_movimientos_revierte_a_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['editado_por_id'], ['id'], referent_schema='stock_charles_schema')
        batch_op.create_foreign_key(None, 'usuarios', ['eliminado_por_id'], ['id'], referent_schema='stock_charles_schema')
        batch_op.create_foreign_key(None, 'caja_movimientos', ['revierte_a_id'], ['id'], referent_schema='stock_charles_schema')
        batch_op.create_foreign_key(None, 'caja_turnos', ['turno_id'], ['id'], referent_schema='stock_charles_schema')
        batch_op.create_foreign_key(None, 'usuarios', ['anulado_por_id'], ['id'], referent_schema='stock_charles_schema')
        batch_op.create_foreign_key(None, 'usuarios', ['creado_por_id'], ['id'], referent_schema='stock_charles_schema')

    with op.batch_alter_table('caja_movimientos_borrados', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('caja_movimientos_borrados_borrado_por_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('caja_movimientos_borrados_movimiento_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['borrado_por_id'], ['id'], referent_schema='stock_charles_schema')
        batch_op.create_foreign_key(None, 'caja_movimientos', ['movimiento_id'], ['id'], referent_schema='stock_charles_schema')

    with op.batch_alter_table('caja_movimientos_editados', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('caja_movimientos_editados_movimiento_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('caja_movimientos_editados_editado_por_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'caja_movimientos', ['movimiento_id'], ['id'], referent_schema='stock_charles_schema')
        batch_op.create_foreign_key(None, 'usuarios', ['editado_por_id'], ['id'], referent_schema='stock_charles_schema')

    with op.batch_alter_table('caja_turnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('turno', sa.String(length=10), nullable=True))
        batch_op.drop_constraint(batch_op.f('caja_turnos_abierto_por_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('caja_turnos_cerrado_por_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('caja_turnos_inicio_editado_por_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['cerrado_por_id'], ['id'], referent_schema='stock_charles_schema')
        batch_op.create_foreign_key(None, 'usuarios', ['abierto_por_id'], ['id'], referent_schema='stock_charles_schema')
        batch_op.create_foreign_key(None, 'usuarios', ['inicio_editado_por_id'], ['id'], referent_schema='stock_charles_schema')

    with op.batch_alter_table('libros_bajas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('libros_bajas_libro_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'libros', ['libro_id'], ['id'], referent_schema='stock_charles_schema')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libros_bajas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('libros_bajas_libro_id_fkey'), 'libros', ['libro_id'], ['id'])

    with op.batch_alter_table('caja_turnos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('caja_turnos_inicio_editado_por_id_fkey'), 'usuarios', ['inicio_editado_por_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('caja_turnos_cerrado_por_id_fkey'), 'usuarios', ['cerrado_por_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('caja_turnos_abierto_por_id_fkey'), 'usuarios', ['abierto_por_id'], ['id'])
        batch_op.drop_column('turno')
        batch_op.drop_column('fecha')

    with op.batch_alter_table('caja_movimientos_editados', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('caja_movimientos_editados_editado_por_id_fkey'), 'usuarios', ['editado_por_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('caja_movimientos_editados_movimiento_id_fkey'), 'caja_movimientos', ['movimiento_id'], ['id'])

    with op.batch_alter_table('caja_movimientos_borrados', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('caja_movimientos_borrados_movimiento_id_fkey'), 'caja_movimientos', ['movimiento_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('caja_movimientos_borrados_borrado_por_id_fkey'), 'usuarios', ['borrado_por_id'], ['id'])

    with op.batch_alter_table('caja_movimientos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('caja_movimientos_revierte_a_id_fkey'), 'caja_movimientos', ['revierte_a_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('caja_movimientos_creado_por_id_fkey'), 'usuarios', ['creado_por_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('caja_movimientos_editado_por_id_fkey'), 'usuarios', ['editado_por_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('caja_movimientos_anulado_por_id_fkey'), 'usuarios', ['anulado_por_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('caja_movimientos_eliminado_por_id_fkey'), 'usuarios', ['eliminado_por_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('caja_movimientos_turno_id_fkey'), 'caja_turnos', ['turno_id'], ['id'])

    with op.batch_alter_table('caja_inicio_detalles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('caja_inicio_detalles_editado_por_id_fkey'), 'usuarios', ['editado_por_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('caja_inicio_detalles_turno_id_fkey'), 'caja_turnos', ['turno_id'], ['id'])

    with op.batch_alter_table('caja_arqueos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('caja_arqueos_realizado_por_id_fkey'), 'usuarios', ['realizado_por_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('caja_arqueos_turno_id_fkey'), 'caja_turnos', ['turno_id'], ['id'])

    with op.batch_alter_table('auditoria_eventos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('auditoria_eventos_usuario_id_fkey'), 'usuarios', ['usuario_id'], ['id'])

    # ### end Alembic commands ###
